version: "3.8"

services:
  app:
    container_name: vietentertainment-viet-frontend
    image: vietentertainment2023/frontend:0.0.1
    environment:
      - REACT_APP_API=${REACT_APP_API}
      - REACT_APP_MOCK_API=${REACT_APP_MOCK_API}
      - REACT_APP_ENV=${REACT_APP_ENV}
      - REACT_KEYCLOAK_API=${REACT_KEYCLOAK_API}
    build:
      context: .
    ports:
      - "3000:80"
    restart: unless-stopped