version: "3.8"

services:
  app:
    container_name: vietentertainment-viet-frontend
    image: vietentertainment2023/frontend:latest
    environment:
      - REACT_APP_API=${REACT_APP_API}
      - REACT_APP_MOCK_API=${REACT_APP_MOCK_API}
      - REACT_APP_ENV=${REACT_APP_ENV}
      - REACT_KEYCLOAK_API=${REACT_KEYCLOAK_API}
      - REACT_APP_DOMAIN=${REACT_APP_DOMAIN}
    ports:
      - "3000:80"
    restart: unless-stopped
