export const CHANGE_PRICE_RANGE = 'App/SearchResultPage/CHANGE_PRICE_RANGE';
export const CHANGE_EVENT_PRICE_RANGE =
  'App/EventSearchResultPage/CHANGE_EVENT_PRICE_RANGE';
export const MAX_DEFAULT = 100000000;
export const MIN_DEFAULT = 100000;
export const CHANGE_OWN_PACKAGE_PRICE_RANGE =
  'App/MyPackage/CHANGE_PACKAGE_PRICE_RANGE';
export const CHANGE_OWN_EVENT_PRICE_RANGE =
  'App/MyEvents/CHANGE_OWN_EVENT_PRICE_RANGE';
